r"""
derive_canonical.py  --  wave-physics-cap2

Reads canonical_params.json (the single source of truth), derives every
quantity quoted in Chapter 2, and emits a LaTeX macro file
(canonical_macros.tex) that the manuscript \input's. No physical number is
typed by hand in the .tex; each \newcommand traces to this script.

Derived here:
  - dispersive shifts chi_i and ratios
  - transverse exchange J (dispersive formula)
  - ZZ level shift xi_ZZ (exact diagonalization, via ok_zz_exact_diagonalization)
  - harmonic-sum T1_total and T2 from the per-channel breakdown
  - gate-fidelity block (pass-through of ratified values, with consistency check)

Run:  python3 derive_canonical.py
"""

import json
import numpy as np
from ok_zz_exact_diagonalization import compute_zz, perturbative_xi

with open("canonical_params.json") as f:
    P = json.load(f)


def chi(g, Delta, alpha):
    """Dispersive shift including anharmonicity (GHz in -> GHz out)."""
    return (g**2 / Delta) * (alpha / (Delta + alpha))


def derive_point(name):
    op = P["operating_points"][name]
    wq1, wq2, wr = op["omega_q1_GHz"], op["omega_q2_GHz"], op["omega_r_GHz"]
    g1, g2 = op["g1_GHz"], op["g2_GHz"]
    a1, a2 = op["alpha1_GHz"], op["alpha2_GHz"]
    D1, D2 = wq1 - wr, wq2 - wr
    Dq = wq1 - wq2

    chi1 = chi(g1, D1, a1)
    chi2 = chi(g2, D2, a2)
    J = 0.5 * g1 * g2 * (1.0 / D1 + 1.0 / D2)

    zz = compute_zz(wq1, wq2, wr, g1, g2, a1, a2, label=name)
    xi = zz["xi_ZZ_kHz"]

    return dict(
        Delta1_MHz=D1 * 1e3, Delta2_MHz=D2 * 1e3, Dq_MHz=Dq * 1e3,
        chi1_MHz=chi1 * 1e3, chi2_MHz=chi2 * 1e3,
        J_MHz=J * 1e3, xi_ZZ_kHz=xi,
        ratio=abs(J * 1e3 / (xi * 1e-3)),  # |J|/|xi| dimensionless
    )


def derive_decoherence():
    d = P["decoherence_breakdown_innovation_us"]
    channels = [d["T1_dielectric"], d["T1_quasiparticle"], d["T1_radiative"],
                d["T1_TLS"], d["T1_Purcell"]]
    T1 = 1.0 / sum(1.0 / c for c in channels)
    Tphi = d["T_phi_us"]
    T2 = 1.0 / (1.0 / (2 * T1) + 1.0 / Tphi)
    return dict(T1_total_us=T1, T2_us=T2, T2_echo_us=d["T2_echo_us"])


def derive_thermal():
    """Thermal occupation and the thermal-limited fidelity ceiling at the fixed
    300 GHz / 4 K operating point. Lowering T is excluded by design."""
    h = 6.62607015e-34
    kB = 1.380649e-23
    th = P["thermal_300GHz_4K"]
    f = th["qubit_freq_GHz"] * 1e9
    T = th["T_operating_K"]
    x = h * f / (kB * T)
    n_th = 1.0 / (np.exp(x) - 1.0)
    eps_thermal = n_th * 0.5            # chapter model
    F_ceiling = 1.0 - eps_thermal       # ceiling at fixed 300 GHz / 4 K
    return dict(x=x, n_th_pct=n_th * 100, eps_thermal_pct=eps_thermal * 100,
                F_ceiling_pct=F_ceiling * 100)


def fmt(x, nd):
    return f"{x:.{nd}f}"


def main():
    base = derive_point("baseline_mK")
    innov = derive_point("innovation_300GHz")
    dec = derive_decoherence()
    th = derive_thermal()
    gf = P["gate_fidelity"]

    # t_CNOT is DERIVED, not asserted: t_CNOT = epsilon_decoh * T2_echo
    t_CNOT_ns = (gf["epsilon_decoh_percent"] / 100.0) * dec["T2_echo_us"] * 1e3

    lines = []
    lines.append("% canonical_macros.tex -- AUTO-GENERATED by derive_canonical.py")
    lines.append("% Do not edit by hand. Edit canonical_params.json and re-run.")
    lines.append("% ---- Baseline (mK validation two-qubit) ----")
    lines.append(r"\newcommand{\BaseDeltaOne}{" + fmt(base["Delta1_MHz"]/1e3, 1) + r"}")   # GHz
    lines.append(r"\newcommand{\BaseDeltaTwo}{" + fmt(base["Delta2_MHz"]/1e3, 1) + r"}")
    lines.append(r"\newcommand{\BaseDeltaQ}{" + fmt(base["Dq_MHz"], 0) + r"}")            # MHz
    lines.append(r"\newcommand{\BaseChiOne}{" + fmt(base["chi1_MHz"], 2) + r"}")
    lines.append(r"\newcommand{\BaseChiOneMag}{" + fmt(abs(base["chi1_MHz"]), 2) + r"}")
    lines.append(r"\newcommand{\BaseChiTwo}{" + fmt(base["chi2_MHz"], 2) + r"}")
    lines.append(r"\newcommand{\BaseChiTwoMag}{" + fmt(abs(base["chi2_MHz"]), 2) + r"}")
    lines.append(r"\newcommand{\BaseJ}{" + fmt(base["J_MHz"], 1) + r"}")                  # MHz
    lines.append(r"\newcommand{\BaseJmag}{" + fmt(abs(base["J_MHz"]), 1) + r"}")
    lines.append(r"\newcommand{\BaseXiZZ}{" + fmt(base["xi_ZZ_kHz"], 0) + r"}")           # kHz
    lines.append(r"\newcommand{\BaseXiZZmag}{" + fmt(abs(base["xi_ZZ_kHz"]), 0) + r"}")
    lines.append(r"\newcommand{\BaseRatioJZeta}{" + fmt(base["ratio"], 0) + r"}")
    lines.append("% ---- Innovation (300 GHz / 4 K) ----")
    lines.append(r"\newcommand{\InnDeltaQ}{" + fmt(innov["Dq_MHz"], 0) + r"}")            # MHz
    lines.append(r"\newcommand{\InnDeltaOne}{" + fmt(innov["Delta1_MHz"]/1e3, 1) + r"}")   # GHz
    lines.append(r"\newcommand{\InnDeltaTwo}{" + fmt(innov["Delta2_MHz"]/1e3, 1) + r"}")   # GHz
    lines.append(r"\newcommand{\InnChiOne}{" + fmt(innov["chi1_MHz"], 2) + r"}")
    lines.append(r"\newcommand{\InnChiTwo}{" + fmt(innov["chi2_MHz"], 2) + r"}")
    lines.append(r"\newcommand{\InnRatioOne}{" + fmt(abs(innov["Delta1_MHz"])/80.0, 1) + r"}")
    lines.append(r"\newcommand{\InnRatioTwo}{" + fmt(abs(innov["Delta2_MHz"])/80.0, 1) + r"}")
    lines.append(r"\newcommand{\InnAlpha}{" + fmt(P['operating_points']['innovation_300GHz']['alpha1_GHz'], 0) + r"}")  # GHz
    lines.append(r"\newcommand{\InnJ}{" + fmt(innov["J_MHz"], 1) + r"}")                  # MHz
    lines.append(r"\newcommand{\InnJmag}{" + fmt(abs(innov["J_MHz"]), 1) + r"}")
    lines.append(r"\newcommand{\InnXiZZ}{" + fmt(innov["xi_ZZ_kHz"], 0) + r"}")           # kHz
    lines.append(r"\newcommand{\InnXiZZmag}{" + fmt(abs(innov["xi_ZZ_kHz"]), 0) + r"}")
    lines.append(r"\newcommand{\InnRatioJZeta}{" + fmt(innov["ratio"], 0) + r"}")
    lines.append("% ---- Decoherence (300 GHz / 4 K) ----")
    lines.append(r"\newcommand{\TOneTotal}{" + fmt(dec["T1_total_us"], 1) + r"}")         # us
    lines.append(r"\newcommand{\TTwo}{" + fmt(dec["T2_us"], 1) + r"}")
    lines.append(r"\newcommand{\TTwoEcho}{" + fmt(dec["T2_echo_us"], 1) + r"}")
    lines.append("% ---- Gate fidelity ----")
    lines.append(r"\newcommand{\FCNOT}{" + fmt(gf["F_CNOT_4K_percent"], 1) + r"}")
    lines.append(r"\newcommand{\FCNOTbase}{" + fmt(gf["F_CNOT_baseline_percent"], 1) + r"}")
    lines.append(r"\newcommand{\Fsingle}{" + fmt(100.0 - gf["epsilon_single_percent"], 2) + r"}")
    lines.append(r"\newcommand{\FdecohCeiling}{" + fmt(gf["decoherence_ceiling_percent"], 1) + r"}")
    lines.append(r"\newcommand{\EpsDecoh}{" + fmt(gf["epsilon_decoh_percent"], 2) + r"}")
    lines.append(r"\newcommand{\tCNOT}{" + fmt(t_CNOT_ns, 1) + r"}")
    lines.append("% ---- Thermal ceiling at fixed 300 GHz / 4 K ----")
    lines.append(r"\newcommand{\nThermal}{" + fmt(th["n_th_pct"], 2) + r"}")          # percent
    lines.append(r"\newcommand{\EpsThermal}{" + fmt(th["eps_thermal_pct"], 2) + r"}")  # percent
    lines.append(r"\newcommand{\Fceiling}{" + fmt(th["F_ceiling_pct"], 2) + r"}")      # percent

    with open("canonical_macros.tex", "w") as f:
        f.write("\n".join(lines) + "\n")

    print("\n" + "=" * 64)
    print("DERIVED CANONICAL VALUES")
    print("=" * 64)
    print(f"Baseline : J = {base['J_MHz']:+.1f} MHz, xi_ZZ = {base['xi_ZZ_kHz']:+.0f} kHz, "
          f"|J/xi| = {base['ratio']:.0f}")
    print(f"           chi1 = {base['chi1_MHz']:+.2f} MHz, chi2 = {base['chi2_MHz']:+.2f} MHz")
    print(f"Innov    : J = {innov['J_MHz']:+.1f} MHz, xi_ZZ = {innov['xi_ZZ_kHz']:+.0f} kHz, "
          f"|J/xi| = {innov['ratio']:.0f}")
    print(f"Decoh    : T1_total = {dec['T1_total_us']:.2f} us, T2 = {dec['T2_us']:.2f} us, "
          f"T2_echo = {dec['T2_echo_us']:.1f} us")
    print(f"Fidelity : F_CNOT = {gf['F_CNOT_4K_percent']:.1f}%, "
          f"eps_decoh = {gf['epsilon_decoh_percent']:.2f}%, t_CNOT(derived) = {t_CNOT_ns:.1f} ns")
    print(f"Thermal  : n_th = {th['n_th_pct']:.2f}%, eps_thermal = {th['eps_thermal_pct']:.2f}%, "
          f"F_ceiling = {th['F_ceiling_pct']:.2f}% (fixed 300 GHz / 4 K)")
    print("\nWrote canonical_macros.tex")


if __name__ == "__main__":
    main()
